name: Tests
on: [ push, pull_request ]
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: mergestat-linux-amd64
          - os: macos-latest
            asset_name: mergestat-macos-amd64

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
        id: go

      - name: Check out source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install libgit2
        run: make libgit2

      - name: Vet
        run: make vet

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.0
          make lint-ci

      - name: Test
        run: make test-cover

      - name: Upload coverage
        uses: codecov/codecov-action@v3